[package]
name = "nix-editor"
version = "0.2.3"
edition = "2021"
license = "GPL-3.0-or-later"
description = "Some functions to modify NixOS configuration files"
repository = "https://github.com/vlinkz/nix-editor/"
readme = "README.md"
include = [
  "src/*",
  "Cargo.toml",
  "LICENSE*",
  "README.md",
]

[dependencies]
serde_json = "1.0.79"
clap =  { version = "3.1.6", features = ["derive"] }
rnix = "0.10.1"
colored = "2.0.0"
