[package]
name = "nix-editor"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde_json = "1.0.74"
clap =  { version = "3.0.7", features = ["derive"] }
rnix = "0.10.1"
colored = "2.0.0"