[package]
name = "nix-editor"
version = "0.2.8"
edition = "2021"
license = "GPL-3.0-or-later"
description = "Some functions to modify NixOS configuration files"
repository = "https://github.com/vlinkz/nix-editor/"
readme = "README.md"
include = [
  "src/*",
  "Cargo.toml",
  "LICENSE*",
  "README.md",
]

[dependencies]
clap =  { version = "3.1.8", features = ["derive"] }
rnix = "0.10.1"
owo-colors = "3.3.0"
